### ISSUE TITLE
Custom Data files not being copied to relevant directories

### ISSUE THREAD

**Issue by remib** [mattrayner/cordova-plugin-vuforia#24] opened 2016-05-27 15:32 UTC
I've followed the instructions to use my own data however I can't get it to work. The .dat and .xml files are not copied to the directories on both iOS and Android. I'm using Cordova 6.1.1 along with the latest version of Ionic framework. The plugin works with the test data.

**Comment by mattrayner** [comment] 2016-05-27 15:33
Duplicate of #15 I think - we are currently testing this

**Closed by mattrayner** 2016-05-27 15:33 UTC

**Comment by remib** [comment] 2016-05-27 15:47
Sorry didn't see that!

**Comment by mattrayner** [comment] 2016-05-27 15:47
It's cool 😀
